In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
arr.shape

(2, 3)

In [6]:
arr[1,1]

5

In [8]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.random.random((2,3))

array([[0.01261412, 0.40061872, 0.61840486],
       [0.59485427, 0.87706191, 0.76024375]])

In [15]:
g = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
type(g)

numpy.ndarray

In [16]:
g[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [17]:
g[:2, :2]

array([[1, 2],
       [5, 6]])

In [20]:
g[:,2]

array([ 3,  7, 11])

In [23]:
g[[0,1,0], [0,1,2]] # g (0,0), (1,1), (0,2)

array([1, 6, 3])

In [25]:
g[np.arange(3), [2, 3, 0]]

array([3, 8, 9])

In [28]:
boox_id = g % 2 == 0
boox_id

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [29]:
g[boox_id]

array([ 2,  4,  6,  8, 10, 12])

In [30]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
x

array([[1., 2.],
       [3., 4.]])

In [31]:
y = np.array([[5,6],[7,8]], dtype=np.float64)

In [32]:
x+y

array([[ 6.,  8.],
       [10., 12.]])

In [33]:
x*y

array([[ 5., 12.],
       [21., 32.]])

In [34]:
x.dot(y)

array([[19., 22.],
       [43., 50.]])

In [35]:
np.dot(x,y)

array([[19., 22.],
       [43., 50.]])

In [37]:
np.sum(x)

10.0

In [38]:
np.sum(x, axis=0)

array([4., 6.])

In [39]:
np.sum(x,axis = 1)

array([3., 7.])

In [40]:
x.T

array([[1., 3.],
       [2., 4.]])

In [41]:
x + np.array([7,8])

array([[ 8., 10.],
       [10., 12.]])

In [43]:
v = np.array([[1,2,3]])
np.tile(v, (4,2))

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [44]:
v = np.array([1,2,3])
w = np.array([4,5])
x = np.array([[1,2,3], [4,5,6]])

print(x + v)
print((x.T + w).T)
print(x*2)

[[2 4 6]
 [5 7 9]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 2  4  6]
 [ 8 10 12]]
